#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, inclduing C++ tesbench
verilator -Wall --cc --trace top.sv  --exe group21_tb.cpp

# build cpp project via maqke automatically generated by verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

obj_dir/Vtop
