#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f cpu.vcd

# run Verilator to translate Verilog into C++, inclduing C++ tesbench
verilator -Wall --cc --trace cpu.sv  --exe cpu_tb.cpp

# build cpp project via maqke automatically generated by verilator
make -j -C obj_dir/ -f Vcpu.mk Vcpu

obj_dir/Vcpu
