#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f topalu.vcd

# run Verilator to translate Verilog into C++, inclduing C++ tesbench
verilator -Wall --cc --trace topalu.sv  --exe topalu_tb.cpp

# build cpp project via maqke automatically generated by verilator
make -j -C obj_dir/ -f Vtopalu.mk Vtopalu

obj_dir/Vtopalu
