#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f memory.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace memory.sv --exe cache_1wtb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vmemory.mk Vmemory

# run executable simulation file
obj_dir/Vmemory