#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top_memory.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top_memory.sv --exe cache_1tb.cpp -y generics

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_memory.mk Vtop_memory

# run executable simulation file
obj_dir/Vtop_memory
