#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f sign_extend.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace sign_extend.sv --exe sign_extend_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsign_extend.mk Vsign_extend

# run executable simulation file
obj_dir/Vsign_extend
