#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f data_mem.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace data_mem.sv --exe data_mem_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdata_mem.mk Vdata_mem

# run executable simulation file
obj_dir/Vdata_mem