#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top_pc.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top_pc.sv --exe top_pc_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_pc.mk Vtop_pc

# run executable simulation file
obj_dir/Vtop_pc
