#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f pcsrc_logic.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace pcsrc_logic.sv --exe pcsrc_logic_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vpcsrc_logic.mk Vpcsrc_logic

# run executable simulation file
obj_dir/Vpcsrc_logic
