#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top_control_unit.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top_control_unit.sv --exe top_control_unit_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_control_unit.mk Vtop_control_unit

# run executable simulation file
obj_dir/Vtop_control_unit
