#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f control_unit.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace control_unit.sv --exe control_unit_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcontrol_unit.mk Vcontrol_unit

# run executable simulation file
obj_dir/Vcontrol_unit
