#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f modified.vcd

# run Verilator to translate Verilog into C++, inclduing C++ tesbench
verilator -Wall --cc --trace modified.sv  --exe top.cpp

# build cpp project via maqke automatically generated by verilator
make -j -C obj_dir/ -f Vmodified.mk Vmodified

obj_dir/Vmodified
